### PR TITLE
Fix format-security errors in ComputeTester

### PR DESCRIPTION
**Pull request by 1sixth**
## Motivation

I encountered compilation errors while packaging ROCm Optiq for a Linux distro:

```
FAILED: [code=1] CMakeFiles/roc-optiq.dir/src/view/src/compute/rocprofvis_compute_tester.cpp.o
/nix/store/z4c6k0mrlkwl3s4w9ysxc8vq1wylm3ms-gcc-wrapper-15.3.0/bin/g++ -DFMT_SHARED -DIMGUI_DEFINE_MATH_OPERATORS -DNFD_PORTAL -DROCPROFVIS_HAVE_NATIVE_FILE_DIALOG -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSPDLOG_SHARED_LIB -I/build/source/src/model/inc -I/build/source/src/app/inc -I/build/source/resources -I/build/source/src/controller/inc -I/build/source/src/view/inc -I/build/source/src/view/src -I/build/source/src/view/src/model -I/build/source/src/view/src/icons -I/build/source/src/view/src/widgets -I/build/source/src/core/inc -I/build/source/thirdparty -I/build/source/thirdparty/imgui -I/build/source/thirdparty/imgui/backends -I/build/source/thirdparty/implot -I/build/source/src/controller/../model/inc -I/build/source/src/controller/../core/inc -I/build/source/src/controller/src -I/build/source/thirdparty/jsoncpp -I/build/source/thirdparty/nativefiledialog-extended/src/include -I/build/source/thirdparty/ImGuiFileDialog -DVK_PROTOTYPES -O3 -DNDEBUG -std=gnu++17 -MD -MT CMakeFiles/roc-optiq.dir/src/view/src/compute/rocprofvis_compute_tester.cpp.o -MF CMakeFiles/roc-optiq.dir/src/view/src/compute/rocprofvis_compute_tester.cpp.o.d -o CMakeFiles/roc-optiq.dir/src/view/src/compute/rocprofvis_compute_tester.cpp.o -c /build/source/src/view/src/compute/rocprofvis_compute_tester.cpp
/build/source/src/view/src/compute/rocprofvis_compute_tester.cpp: In member function 'virtual void RocProfVis::View::ComputeTester::Render()':
/build/source/src/view/src/compute/rocprofvis_compute_tester.cpp:133:32: error: format not a string literal and no format arguments [-Werror=format-security]
  133 |                     ImGui::Text(workload.system_info[0][i].c_str());
      |                     ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/build/source/src/view/src/compute/rocprofvis_compute_tester.cpp:135:32: error: format not a string literal and no format arguments [-Werror=format-security]
  135 |                     ImGui::Text(workload.system_info[1][i].c_str());
      |                     ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/build/source/src/view/src/compute/rocprofvis_compute_tester.cpp:154:32: error: format not a string literal and no format arguments [-Werror=format-security]
  154 |                     ImGui::Text(workload.profiling_config[0][i].c_str());
      |                     ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/build/source/src/view/src/compute/rocprofvis_compute_tester.cpp:156:32: error: format not a string literal and no format arguments [-Werror=format-security]
  156 |                     ImGui::Text(workload.profiling_config[1][i].c_str());
      |                     ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/build/source/src/view/src/compute/rocprofvis_compute_tester.cpp:276:48: error: format not a string literal and no format arguments [-Werror=format-security]
  276 |                                     ImGui::Text(entry->description.c_str());
      |                                     ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/build/source/src/view/src/compute/rocprofvis_compute_tester.cpp:279:48: error: format not a string literal and no format arguments [-Werror=format-security]
  279 |                                     ImGui::Text(entry->unit.c_str());
      |                                     ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
/build/source/src/view/src/compute/rocprofvis_compute_tester.cpp:336:28: error: format not a string literal and no format arguments [-Werror=format-security]
  336 |                 ImGui::Text(kernel.second.name.c_str());
      |                 ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/build/source/src/view/src/compute/rocprofvis_compute_tester.cpp:428:28: error: format not a string literal and no format arguments [-Werror=format-security]
  428 |                 ImGui::Text(std::to_string(id).c_str());
      |                 ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/build/source/src/view/src/compute/rocprofvis_compute_tester.cpp:563:44: error: format not a string literal and no format arguments [-Werror=format-security]
  563 |                                 ImGui::Text(metric->entry->name.c_str());
      |                                 ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/build/source/src/view/src/compute/rocprofvis_compute_tester.cpp:567:44: error: format not a string literal and no format arguments [-Werror=format-security]
  567 |                                 ImGui::Text(value.first.c_str());
      |                                 ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
/build/source/src/view/src/compute/rocprofvis_compute_tester.cpp:617:36: error: format not a string literal and no format arguments [-Werror=format-security]
  617 |                         ImGui::Text(metric->entry->name.c_str());
      |                         ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/build/source/src/view/src/compute/rocprofvis_compute_tester.cpp:621:36: error: format not a string literal and no format arguments [-Werror=format-security]
  621 |                         ImGui::Text(value.first.c_str());
      |                         ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
cc1plus: some warnings being treated as errors
```

The flag `-Werror=format-security` is enabled by default in [lots](https://nixos.org/manual/nixpkgs/stable/#sec-hardening-flags-enabled-by-default) [of](https://manpages.debian.org/trixie/dpkg-dev/dpkg-buildflags.1.en.html#format) [Linux](https://wiki.ubuntu.com/ToolChain/CompilerFlags#A-Wformat_-Wformat-security) [distros](https://fedoraproject.org/wiki/Changes/FormatSecurity). So I figure I should fix it upstream.

## Technical Details

This PR fixes the compilation errors in `ComputeTester::Render()` by using `ImGui::TextUnformatted` instead of `ImGui::Text` to display dynamic strings.

## Test Plan

- Build on Linux with GCC 15.3.0 and `-Wformat -Werror=format-security` to reproduce the compilation failure.
- Apply the fix and rebuild with the same configuration.

## Test Result

- Before the fix, compilation failed with 12 `-Werror=format-security` errors in `rocprofvis_compute_tester.cpp`.
- After the fix, the full build completed successfully.

## Submission Checklist

- [x] Look over the contributing guidelines at https://github.com/ROCm/TheRock/blob/main/GOVERNANCE.md#pull-requests.

### CODE REVIEW

**Review by drchen-amd — APPROVED** [review]
Thanks for your contribution. Much appreciated.
